### ISSUE TITLE
top bar hidden

### ISSUE THREAD

**Issue by ceceghini** [bvobart/firefox-nativefy#1]
Hi

I use firefox with gnome.

all works, but the top bar with maximize e minimize button is not showd

what could it be?

**Comment by bvobart** [comment]
Hi, you're the first person besides myself that I know of that also uses this tool, thanks! :)

Firefox (both on GNOME as well as on KDE) turn off the default window decorations and render their own custom window decorations. Those minimize, maximise and close buttons are shown in Firefox' menu bar. And that menu bar's visibility is affected by these lines of user CSS injected by firefox-nativefy:

```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
#TabsToolbar {visibility: collapse;}
#navigator-toolbox {visibility: collapse;}
```

Try removing the `#navigator-toolbox` line and then seeing if the menu bar appears. If it does not, try pressing [Alt](https://support.mozilla.org/en-US/kb/restore-menu-bar-firefox). Let me know if that works for you; if it does, I'll make it the default for `firefox-nativefy.sh` that that menu bar is not hidden by CSS, but just hidden as in you need to press Alt for it to appear.

Alternatively, in GNOME you can also [try Meta+RightClick](https://www.reddit.com/r/gnome/comments/1fg0snt/possible_to_force_an_application_to_use_gnome/) to show the GNOME window menu. Meta+LeftClick dragging allows you to move the window.
